Update installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -55,21 +55,29 @@ else
 fi
 sudo sysctl -p
 
-# Step 7: Install the node from the Github repo
+# Step 7: Install the node and the client from the Github repo
 cd ~/ || { echo "Failed to change directory to $HOME! Exiting..."; exit 1; }
 if [[ -d "ceremonyclient" ]]; then
   echo "ceremonyclient directory already exists. I don't want to overwrite your ceremonyclient, so I will skip the install..."
 else
   echo "Downloading the node software..."
   git clone https://github.com/QuilibriumNetwork/ceremonyclient.git || { echo "Failed to clone the repository! Exiting..."; exit 1; }
-  cd ceremonyclient/node
 fi
 
+# Build the client
+echo "Building the client..."
+cd ceremonyclient/client
+go build -o qclient || { echo "Failed to build the client! Exiting..."; exit 1; }
+
+# Change directory to the node directory
+echo "Changing directory to node..."
+cd ../node || { echo "Failed to change directory to node! Exiting..."; exit 1; }
+
 # Step 8: Letting the node run for 10 minutes
-echo "Running the node run for 10 minutes..."
+echo "Running the node for 10 minutes..."
 GOEXPERIMENT=arenas go run ./... > /dev/null 2>&1 &  # Redirect output to /dev/null
 countdown() {
-    secs=$1         # Assign the input argument (180) to the variable 'secs'
+    secs=$1         # Assign the input argument (600) to the variable 'secs'
     while [ $secs -gt 0 ]; do
         printf "\r%02d:%02d remaining" $(($secs/60)) $(($secs%60)) # Print the remaining time (mm:ss) with a carriage return (\r) to overwrite the previous line
         sleep 1     # Wait for 1 second
@@ -79,9 +87,11 @@ countdown() {
 }
 countdown 600 || { echo "Failed to wait! Exiting..."; exit 1; }
 
+
 # Step 9: Prompt for reboot
 echo "Node setup is finished."
 echo "Type 'sudo reboot' and press Enter to reboot your server."
 echo "When you have logged back in, run 'cd ~/ceremonyclient/node/', open a new tmux session with 'tmux new-session -s quil' and run 'bash poor_mans_cd.sh'."
 echo "Then detach from the tmux session without ceasing it by pressing Ctrl-B and then pressing D."
 echo "Remember to make backup copies of the keys.yml and config.yml files, folder ~/ceremonyclient/node/.config."
+echo "Always check the online guide for useful commands and troubleshooting guides."
