Update installer-service

diff --git a/installer-service b/installer-service
--- a/installer-service
+++ b/installer-service
@@ -1,1 +1,157 @@
+#!/bin/bash  -i
+
+# Step 0: Welcome
+echo "This script will install your Quilibrium node and start it."
+echo "Made by LaMat with 0xOzgur.eth help"
+echo "Processing..."
+sleep 5  # Add a 5-second delay
+
+# Define a function for displaying exit messages
+exit_message() {
+    echo "There was an error during the script execution and the process stopped. No worries!"
+    echo "You can try to run the script from scratch again."
+    echo "If you still receive an error, you may want to proceed manually, step by step instead of using the auto-installer."
+}
+
+# Step 1: Check sudo availability
+if ! [ -x "$(command -v sudo)" ]; then
+  echo "Sudo is not installed! This script requires sudo to run. Exiting..." >&2
+  exit_message
+  exit 1
+fi
+
+# Step 2: Update and Upgrade the Machine
+echo "Updating the machine"
+echo "Processing..."
+sleep 2  # Add a 2-second delay
+sudo apt-get update
+sudo apt-get upgrade -y
+
+# Step 3: Install required packages
+echo "Installing useful packages..."
+sudo apt-get install git wget tmux tar -y || { echo "Failed to install useful packages! Exiting..."; exit_message; exit 1; }
+
+# Step 4: Download and extract Go
+if [[ $(go version) == *"go1.20.1"* || $(go version) == *"go1.20.2"* || $(go version) == *"go1.20.3"* || $(go version) == *"go1.20.4"* ]]; then
+  echo "Correct version of Go is already installed, moving on..."
+else
+  echo "Installing the necessary version of Go..."
+  wget -4 https://go.dev/dl/go1.20.14.linux-amd64.tar.gz || { echo "Failed to download Go! Exiting..."; exit_message; exit 1; }
+  sudo tar -C /usr/local -xzf go1.20.14.linux-amd64.tar.gz || { echo "Failed to extract Go! Exiting..."; exit_message; exit 1; }
+  sudo rm go1.20.14.linux-amd64.tar.gz || { echo "Failed to remove downloaded archive! Exiting..."; exit_message; exit 1; }
+fi
+
+# Step 5: Set Go environment variables
+echo "Setting Go environment variables..."
+
+# Check if PATH is already set
+if grep -q 'export PATH=$PATH:/usr/local/go/bin' ~/.bashrc; then
+    echo "PATH already set in ~/.bashrc."
+else
+    echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
+    echo "PATH set in ~/.bashrc."
+fi
+
+# Check if GOPATH is already set
+if grep -q "export GOPATH=$HOME/go" ~/.bashrc; then
+    echo "GOPATH already set in ~/.bashrc."
+else
+    echo "export GOPATH=$HOME/go" >> ~/.bashrc
+    echo "GOPATH set in ~/.bashrc."
+fi
+
+# Check if GO111MODULE is already set
+if grep -q "export GO111MODULE=on" ~/.bashrc; then
+    echo "GO111MODULE already set in ~/.bashrc."
+else
+    echo "export GO111MODULE=on" >> ~/.bashrc
+    echo "GO111MODULE set in ~/.bashrc."
+fi
+
+# Check if GOPROXY is already set
+if grep -q "export GOPROXY=https://goproxy.cn,direct" ~/.bashrc; then
+    echo "GOPROXY already set in ~/.bashrc."
+else
+    echo "export GOPROXY=https://goproxy.cn,direct" >> ~/.bashrc
+    echo "GOPROXY set in ~/.bashrc."
+fi
+
+# Source .bashrc to apply changes
+source ~/.bashrc
+sleep 1  # Add a 1-second delay
+
+# Step 6: Adjust network buffer sizes
+echo "Adjusting network buffer sizes..."
+if grep -q "^net.core.rmem_max=600000000$" /etc/sysctl.conf; then
+  echo "net.core.rmem_max=600000000 found inside /etc/sysctl.conf, skipping..."
+else
+  echo -e "\n# Change made to increase buffer sizes for better network performance for ceremonyclient\nnet.core.rmem_max=600000000" | sudo tee -a /etc/sysctl.conf > /dev/null
+fi
+if grep -q "^net.core.wmem_max=600000000$" /etc/sysctl.conf; then
+  echo "net.core.wmem_max=600000000 found inside /etc/sysctl.conf, skipping..."
+else
+  echo -e "\n# Change made to increase buffer sizes for better network performance for ceremonyclient\nnet.core.wmem_max=600000000" | sudo tee -a /etc/sysctl.conf > /dev/null
+fi
+sudo sysctl -p
+
+# Step 7: Install gRPCurl
+echo "Installing gRPCurl"
+sleep 1  # Add a 1-second delay
+go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
+
+# Function to check if a UFW rule exists
+ufw_rule_exists() {
+    local rule="$1"
+    sudo ufw status | grep -q "$rule"
+}
+
+# Step 8: Install ufw and configure firewall
+echo "Installing ufw (Uncomplicated Firewall)..."
+sudo apt-get update
+sudo apt-get install ufw -y || { echo "Failed to install ufw! Moving on to the next step..."; }
+
+# Attempt to enable ufw
+echo "Configuring firewall..."
+if command -v ufw >/dev/null 2>&1; then
+    echo "y" | sudo ufw enable || { echo "Failed to enable firewall! No worries, you can do it later manually."; }
+else
+    echo "ufw (Uncomplicated Firewall) is not installed. Skipping firewall configuration."
+fi
+
+# Check if ufw is available and configured
+if command -v ufw >/dev/null 2>&1 && sudo ufw status | grep -q "Status: active"; then
+    # Allow required ports
+    for port in 22 8336 443; do
+        if ! ufw_rule_exists "${port}"; then
+            sudo ufw allow "${port}" || echo "Error: Failed to allow port ${port}! You will need to allow port 8336 manually for the node to connect."
+        fi
+    done
+
+    # Display firewall status
+    sudo ufw status
+    echo "Firewall setup was successful."
+else
+    echo "Failed to configure firewall or ufw is not installed. No worries, you can do it later manually.  Moving on to the next step..."
+fi
+
+# Step 9: Creating some useful folders
+# Create /root/backup/ folder if it doesn't exist already
+echo "Creating /root/backup/ folder..."
+sudo mkdir -p /root/backup/
+echo "Done."
+
+# Create /root/scripts/ folder if it doesn't exist already
+echo "Creating /root/scripts/ folder..."
+sudo mkdir -p /root/scripts/
+echo "Done."
+
+# Create /root/scripts/log/ folder if it doesn't exist already
+echo "Creating /root/scripts/log/ folder..."
+sudo mkdir -p /root/scripts/log/
+echo "Done."
+
+# Step 10: Prompt for reboot
+echo "Server setup is finished"
+echo "Type 'sudo reboot' and press ENTER to reboot your server."
+echo "Then follow the online guide for the next steps to install your Quilibrium node as a service: https://iri.quest/quilibrium-node-guide"
 
