Update installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -23,15 +23,6 @@ sudo ufw allow 443
 sudo ufw allow 8337  # Allow gRPC port
 sudo ufw status || { echo "Failed to configure firewall! Exiting..."; exit 1; }
 
-# Step 4b: Enable gRPC
-echo "Enabling gRPC..."
-cd ~/ceremonyclient/node || { echo "Failed to change directory to ~/ceremonyclient/node! Exiting..."; exit 1; }
-sudo sed -i 's#^listenGrpcMultiaddr:.*$#listenGrpcMultiaddr: /ip4/127.0.0.1/tcp/8337#' .config/config.yml || { echo "Failed to enable gRPC! Exiting..."; exit 1; }
-
-# Step 4c: Enable Stats Collection
-echo "Enabling Stats Collection..."
-sudo sed -i 's#^  engine:$#  engine:\n    statsMultiaddr: "/dns/stats.quilibrium.com/tcp/443"#' .config/config.yml || { echo "Failed to enable Stats Collection! Exiting..."; exit 1; }
-
 # Step 5: Download and extract Go
 echo "Downloading and extracting Go..."
 wget https://go.dev/dl/go1.20.14.linux-amd64.tar.gz || { echo "Failed to download Go! Exiting..."; exit 1; }
@@ -63,6 +54,15 @@ echo "Cloning the repository..."
 cd "$HOME" || { echo "Failed to change directory to $HOME! Exiting..."; exit 1; }
 git clone https://github.com/QuilibriumNetwork/ceremonyclient.git || { echo "Failed to clone the repository! Exiting..."; exit 1; }
 cd ceremonyclient/node || { echo "Failed to change directory to ceremonyclient/node! Exiting..."; exit 1; }
+
+# Step 9b: Enable gRPC
+echo "Enabling gRPC..."
+cd ~/ceremonyclient/node || { echo "Failed to change directory to ~/ceremonyclient/node! Exiting..."; exit 1; }
+sudo sed -i 's#^listenGrpcMultiaddr:.*$#listenGrpcMultiaddr: /ip4/127.0.0.1/tcp/8337#' .config/config.yml || { echo "Failed to enable gRPC! Exiting..."; exit 1; }
+
+# Step 9c: Enable Stats Collection
+echo "Enabling Stats Collection..."
+sudo sed -i 's#^  engine:$#  engine:\n    statsMultiaddr: "/dns/stats.quilibrium.com/tcp/443"#' .config/config.yml || { echo "Failed to enable Stats Collection! Exiting..."; exit 1; }
 
 # Step 10: Run the node
 echo "Changing directory to $HOME/ceremonyclient/node..."
