Update installer
updated time to run the node after finishing the installation form 5 mins to 10 mins

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -63,8 +63,8 @@ else
   cd ceremonyclient/node
 fi
 
-# Step 8: Letting the node run for 5 minutes
-echo "Running the node run for 5 minutes..."
+# Step 8: Letting the node run for 10 minutes
+echo "Running the node run for 10 minutes..."
 GOEXPERIMENT=arenas go run ./... > /dev/null 2>&1 &  # Redirect output to /dev/null
 countdown() {
     secs=$1         # Assign the input argument (180) to the variable 'secs'
@@ -75,7 +75,7 @@ countdown() {
     done
     printf "\nDone!\n" # After the countdown completes, print "Done!" on a new line
 }
-countdown 300 || { echo "Failed to wait! Exiting..."; exit 1; }
+countdown 600 || { echo "Failed to wait! Exiting..."; exit 1; }
 
 # Step 9: Prompt for reboot
 echo "Node setup is finished."
