Update installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -10,7 +10,9 @@ sudo apt install git -y || { echo "Failed to install git! Exiting..."; exit 1; }
 
 # Step 3: Install required packages
 echo "Installing required packages..."
-sudo apt install speedtest-cli htop tmux -y || { echo "Failed to install required packages! Exiting..."; exit 1; }
+sudo apt-get install curl htop tmux -y || { echo "Failed to install required packages! Exiting..."; exit 1; }
+curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
+sudo apt-get install speedtest -y || { echo "Failed to install speedtest-cli! Exiting..."; exit 1; }
 
 # Step 4: Download and extract Go
 echo "Downloading and extracting Go..."
