Update installer-gRPC-calls

diff --git a/installer-gRPC-calls b/installer-gRPC-calls
--- a/installer-gRPC-calls
+++ b/installer-gRPC-calls
@@ -8,16 +8,25 @@ line_exists() {
 # Step 1: Enable gRPC
 echo "Enabling gRPC..."
 cd "$HOME/ceremonyclient/node" || { echo "Failed to change directory to ~/ceremonyclient/node! Exiting..."; exit 1; }
+
+# Check if the line listenGrpcMultiaddr: /ip4/127.0.0.1/tcp/8337 exists
 if ! line_exists "listenGrpcMultiaddr: /ip4/127.0.0.1/tcp/8337" .config/config.yml; then
-    sudo sed -i 's#^listenGrpcMultiaddr:.*$#listenGrpcMultiaddr: /ip4/127.0.0.1/tcp/8337#' .config/config.yml || { echo "Failed to enable gRPC! Exiting..."; exit 1; }
+    # Check if the line listenGrpcMultiaddr: "" exists
+    if line_exists "listenGrpcMultiaddr: \"\"" .config/config.yml; then
+        # Substitute listenGrpcMultiaddr: "" with listenGrpcMultiaddr: /ip4/127.0.0.1/tcp/8337
+        sudo sed -i 's#^listenGrpcMultiaddr:.*$#listenGrpcMultiaddr: /ip4/127.0.0.1/tcp/8337#' .config/config.yml || { echo "Failed to enable gRPC! Exiting..."; exit 1; }
+    else
+        # Add listenGrpcMultiaddr: /ip4/127.0.0.1/tcp/8337
+        echo "listenGrpcMultiaddr: /ip4/127.0.0.1/tcp/8337" | sudo tee -a .config/config.yml > /dev/null || { echo "Failed to enable gRPC! Exiting..."; exit 1; }
+    fi
 else
     echo "gRPC already enabled."
 fi
 
 # Step 2: Enable Stats Collection
 echo "Enabling Stats Collection..."
-if ! line_exists "statsMultiaddr: \"/dns/stats.quilibrium.com/tcp/443\"" .config/config.yml; then
-    sudo sed -i '/^ *engine:/a\ statsMultiaddr: "/dns/stats.quilibrium.com/tcp/443"' .config/config.yml || { echo "Failed to enable Stats Collection! Exiting..."; exit 1; }
+if ! line_exists "  statsMultiaddr: \"/dns/stats.quilibrium.com/tcp/443\"" .config/config.yml; then
+    sudo sed -i '/^ *engine:/a\  statsMultiaddr: "/dns/stats.quilibrium.com/tcp/443"' .config/config.yml || { echo "Failed to enable Stats Collection! Exiting..."; exit 1; }
 else
     echo "Stats Collection already enabled."
 fi
