Update installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -16,10 +16,11 @@ sudo apt-get install speedtest -y || { echo "Failed to install speedtest-cli! Ex
 
 # Step 4: Configure firewall
 echo "Configuring firewall..."
-sudo ufw enable
+echo "y" | sudo ufw enable || { echo "Failed to enable firewall! Exiting..."; exit 1; }
 sudo ufw allow 22
 sudo ufw allow 8336
 sudo ufw allow 443
+sudo ufw allow 8337  # Allow gRPC port
 sudo ufw status || { echo "Failed to configure firewall! Exiting..."; exit 1; }
 
 # Step 4b: Enable gRPC
