Update installer_2
removed everything related to GO

diff --git a/installer_2 b/installer_2
--- a/installer_2
+++ b/installer_2
@@ -6,81 +6,32 @@ echo "Made with 🔥 by LaMat"
 echo "Processing... ⏳"
 sleep 7  # Add a 7-second delay
 
-# Define a function for displaying exit messages
+# Step 1: Define a function for displaying exit messages
 exit_message() {
     echo "❌ Oops! There was an error during the script execution and the process stopped. No worries!"
     echo "🔄 You can try to run the script from scratch again."
     echo "🛠️ If you still receive an error, you may want to proceed manually, step by step instead of using the auto-installer."
 }
 
-# Step 1: Check sudo availability
+# Step 2: Check sudo availability
 if ! [ -x "$(command -v sudo)" ]; then
   echo "⚠️ Sudo is not installed! This script requires sudo to run. Exiting..."
   exit_message
   exit 1
 fi
 
-# Step 2: Update and Upgrade the Machine
+# Step 3: Update and Upgrade the Machine
 echo "🔄 Updating the machine..."
 echo "Processing... ⏳"
 sleep 2  # Add a 2-second delay
 sudo apt-get update
 sudo apt-get upgrade -y
 
-# Step 3: Install required packages
+# Step 4: Install required packages
 echo "🔧 Installing useful packages..."
 sudo apt-get install git wget tmux tar -y || { echo "❌ Failed to install useful packages! Exiting..."; exit_message; exit 1; }
 
-# Step 4: Download and extract Go
-if [[ $(go version) == *"go1.20.1"* || $(go version) == *"go1.20.2"* || $(go version) == *"go1.20.3"* || $(go version) == *"go1.20.4"* ]]; then
-  echo "✅ Correct version of Go is already installed, moving on..."
-else
-  echo "⬇️ Installing the necessary version of Go..."
-  wget -4 https://go.dev/dl/go1.20.14.linux-amd64.tar.gz || { echo "❌ Failed to download Go! Exiting..."; exit_message; exit 1; }
-  sudo tar -C /usr/local -xzf go1.20.14.linux-amd64.tar.gz || { echo "❌ Failed to extract Go! Exiting..."; exit_message; exit 1; }
-  sudo rm go1.20.14.linux-amd64.tar.gz || { echo "❌ Failed to remove downloaded archive! Exiting..."; exit_message; exit 1; }
-fi
-
-# Step 5: Set Go environment variables
-echo "🌍 Setting Go environment variables..."
-
-# Check if PATH is already set
-if grep -q 'export PATH=$PATH:/usr/local/go/bin' ~/.bashrc; then
-    echo "✅ PATH already set in ~/.bashrc."
-else
-    echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
-    echo "✅ PATH set in ~/.bashrc."
-fi
-
-# Check if GOPATH is already set
-if grep -q "export GOPATH=$HOME/go" ~/.bashrc; then
-    echo "✅ GOPATH already set in ~/.bashrc."
-else
-    echo "export GOPATH=$HOME/go" >> ~/.bashrc
-    echo "✅ GOPATH set in ~/.bashrc."
-fi
-
-# Check if GO111MODULE is already set
-if grep -q "export GO111MODULE=on" ~/.bashrc; then
-    echo "✅ GO111MODULE already set in ~/.bashrc."
-else
-    echo "export GO111MODULE=on" >> ~/.bashrc
-    echo "✅ GO111MODULE set in ~/.bashrc."
-fi
-
-# Check if GOPROXY is already set
-if grep -q "export GOPROXY=https://goproxy.cn,direct" ~/.bashrc; then
-    echo "✅ GOPROXY already set in ~/.bashrc."
-else
-    echo "export GOPROXY=https://goproxy.cn,direct" >> ~/.bashrc
-    echo "✅ GOPROXY set in ~/.bashrc."
-fi
-
-# Source .bashrc to apply changes
-source ~/.bashrc
-sleep 1  # Add a 1-second delay
-
-# Step 6: Adjust network buffer sizes
+# Step 5: Adjust network buffer sizes
 echo "🌐 Adjusting network buffer sizes..."
 if grep -q "^net.core.rmem_max=600000000$" /etc/sysctl.conf; then
   echo "✅ net.core.rmem_max=600000000 found inside /etc/sysctl.conf, skipping..."
@@ -94,10 +45,10 @@ else
 fi
 sudo sysctl -p
 
-# Step 7: Install gRPCurl
+# Step 6: Install gRPCurl
 echo "📦 Installing gRPCurl..."
 sleep 1  # Add a 1-second delay
-go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
+sudo apt-get install grpcurl -y || { echo "❌ Failed to install gRPCurl! Exiting..."; exit_message; exit 1; }
 
 # Function to check if a UFW rule exists
 ufw_rule_exists() {
@@ -105,7 +56,7 @@ ufw_rule_exists() {
     sudo ufw status | grep -q "$rule"
 }
 
-# Step 8: Install ufw and configure firewall
+# Step 7: Install ufw and configure firewall
 echo "🛡️ Installing ufw (Uncomplicated Firewall)..."
 sudo apt-get update
 sudo apt-get install ufw -y || { echo "❌ Failed to install ufw! Moving on to the next step..."; }
@@ -134,7 +85,7 @@ else
     echo "⚠️ Failed to configure firewall or ufw is not installed. No worries, you can do it later manually. Moving on to the next step..."
 fi
 
-# Step 9: Creating some useful folders
+# Step 8: Creating some useful folders
 echo "📂 Creating /root/backup/ folder..."
 sudo mkdir -p /root/backup/
 echo "✅ Done."
@@ -147,8 +98,8 @@ echo "📂 Creating /root/scripts/log/ folder..."
 sudo mkdir -p /root/scripts/log/
 echo "✅ Done."
 
-# Step 10: Prompt for reboot
+# Step 9: Prompt for reboot
 echo "🎉 Server setup is finished!"
 echo "🔄 Type 'sudo reboot' and press ENTER to reboot your server."
 echo "🔗 Then follow the online guide for the next steps"
-echo " to install your Quilibrium node as a service: https://iri.quest/quilibrium-node-guide" 
+echo " to install your Quilibrium node as a service: https://iri.quest/quilibrium-node-guide"
