Update installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -2,9 +2,7 @@
 
 # Step 1: Update package lists
 echo "Updating package lists..."
-DEBIAN_FRONTEND=noninteractive apt-get -y --with-new-pkgs upgrade || { echo "Failed to upgrade packages! Exiting..."; exit 1; }
-
-# Step 3: Install required packages
+sudo apt -q update || { echo "Failed to update package lists! Exiting..."; exit 1; }
 
 # Step 2: Install git
 echo "Installing git..."
@@ -16,14 +14,22 @@ sudo apt-get install curl htop tmux -y || { echo "Failed to install required pac
 curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
 sudo apt-get install speedtest -y || { echo "Failed to install speedtest-cli! Exiting..."; exit 1; }
 
-# Step 4: Download and extract Go
+# Step 4: Configure firewall
+echo "Configuring firewall..."
+sudo ufw enable
+sudo ufw allow 22
+sudo ufw allow 8336
+sudo ufw allow 443
+sudo ufw status || { echo "Failed to configure firewall! Exiting..."; exit 1; }
+
+# Step 5: Download and extract Go
 echo "Downloading and extracting Go..."
 wget https://go.dev/dl/go1.20.14.linux-amd64.tar.gz || { echo "Failed to download Go! Exiting..."; exit 1; }
 sudo tar -xvf go1.20.14.linux-amd64.tar.gz || { echo "Failed to extract Go! Exiting..."; exit 1; }
 sudo mv go /usr/local || { echo "Failed to move Go to /usr/local! Exiting..."; exit 1; }
 sudo rm go1.20.14.linux-amd64.tar.gz || { echo "Failed to remove downloaded archive! Exiting..."; exit 1; }
 
-# Step 5: Set GO environment variables
+# Step 6: Set GO environment variables
 echo "Setting GO environment variables..."
 export PATH="$PATH:/usr/local/go/bin"
 export GOPATH="$HOME/go"
@@ -32,23 +38,23 @@ echo 'export GOPATH="$HOME/go"' >> ~/.bashrc
 source "$HOME/.bashrc"  # Explicitly source the .bashrc file with the full path
 sleep 1  # Add a 1-second delay
 
-# Step 6: Create swap space
+# Step 7: Create swap space
 echo "Creating swap space..."
 sudo mkdir /swap && sudo fallocate -l 24G /swap/swapfile && sudo chmod 600 /swap/swapfile || { echo "Failed to create swap space! Exiting..."; exit 1; }
 sudo mkswap /swap/swapfile && sudo swapon /swap/swapfile || { echo "Failed to set up swap space! Exiting..."; exit 1; }
 sudo bash -c 'echo "/swap/swapfile swap swap defaults 0 0" >> /etc/fstab' || { echo "Failed to update /etc/fstab! Exiting..."; exit 1; }
 
-# Step 7: Adjust network buffer sizes
+# Step 8: Adjust network buffer sizes
 echo "Adjusting network buffer sizes..."
 echo -e "\n# Increase buffer sizes for better network performance\nnet.core.rmem_max=600000000\nnet.core.wmem_max=600000000" | sudo tee -a /etc/sysctl.conf > /dev/null && sudo sysctl -p || { echo "Failed to adjust network buffer sizes! Exiting..."; exit 1; }
 
-# Step 8: Clone the repository
+# Step 9: Clone the repository
 echo "Cloning the repository..."
 cd "$HOME" || { echo "Failed to change directory to $HOME! Exiting..."; exit 1; }
 git clone https://github.com/QuilibriumNetwork/ceremonyclient.git || { echo "Failed to clone the repository! Exiting..."; exit 1; }
 cd ceremonyclient/node || { echo "Failed to change directory to ceremonyclient/node! Exiting..."; exit 1; }
 
-# Step 9: Run the node
+# Step 10: Run the node
 echo "Changing directory to $HOME/ceremonyclient/node..."
 cd "$HOME/ceremonyclient/node" || { echo "Failed to change directory to $HOME/ceremonyclient/node! Exiting..."; exit 1; }
 
@@ -56,7 +62,7 @@ echo "Running the node..."
 GOEXPERIMENT=arenas /usr/local/go/bin/go run ./... > /dev/null 2>&1 &  # Redirect output to /dev/null
 GO_PID=$!
 
-# Step 10: Wait for a few seconds before proceeding
+# Step 11: Wait for a few seconds before proceeding
 echo "Letting the node run for 5 minutes..."
 
 countdown() {
@@ -75,4 +81,3 @@ countdown 300 || { echo "Failed to wait! Exiting..."; exit 1; }
 echo "Node installation is finished."
 echo "Type 'sudo reboot' and press Enter to reboot your server."
 echo "Then login again and follow the instructions of the guide to restart your node."
-
