Check sudo, install tar and wget, check swap
Check availability of sudo on start of script; install tar and alongside htop and tmux, and replace curl with wget in that install line; check for swap first before adding any more

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+# Step 0: Check sudo availability
+if ! [ -x "$(command -v sudo)" ]; then
+  echo "Sudo is not installed! This script requires sudo to run. Exiting..." >&2
+  exit 1
+fi
+
 # Step 1: Update package lists
 echo "Updating package lists..."
 sudo apt -q update || { echo "Failed to update package lists! Exiting..."; exit 1; }
@@ -10,41 +16,43 @@ sudo apt install git -y || { echo "Failed to install git! Exiting..."; exit 1; }
 
 # Step 3: Install required packages
 echo "Installing required packages..."
-sudo apt-get install curl htop tmux -y || { echo "Failed to install required packages! Exiting..."; exit 1; }
+sudo apt-get install wget htop tmux tar -y || { echo "Failed to install required packages! Exiting..."; exit 1; }
 curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
 sudo apt-get install speedtest -y || { echo "Failed to install speedtest-cli! Exiting..."; exit 1; }
 
-# Step 5: Download and extract Go
+# Step 4: Download and extract Go
 echo "Downloading and extracting Go..."
 wget https://go.dev/dl/go1.20.14.linux-amd64.tar.gz || { echo "Failed to download Go! Exiting..."; exit 1; }
 sudo tar -xvf go1.20.14.linux-amd64.tar.gz || { echo "Failed to extract Go! Exiting..."; exit 1; }
 sudo mv go /usr/local || { echo "Failed to move Go to /usr/local! Exiting..."; exit 1; }
 sudo rm go1.20.14.linux-amd64.tar.gz || { echo "Failed to remove downloaded archive! Exiting..."; exit 1; }
 
-# Step 6: Set GO environment variables
+# Step 5: Set GO environment variables
 echo "Setting GO environment variables..."
 echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
 echo 'export GOPATH=$HOME/go' >> ~/.bashrc
 source ~/.bashrc
 sleep 1  # Add a 1-second delay
 
-# Step 7: Create swap space
-echo "Creating swap space..."
-sudo mkdir /swap && sudo fallocate -l 24G /swap/swapfile && sudo chmod 600 /swap/swapfile || { echo "Failed to create swap space! Exiting..."; exit 1; }
-sudo mkswap /swap/swapfile && sudo swapon /swap/swapfile || { echo "Failed to set up swap space! Exiting..."; exit 1; }
-sudo bash -c 'echo "/swap/swapfile swap swap defaults 0 0" >> /etc/fstab' || { echo "Failed to update /etc/fstab! Exiting..."; exit 1; }
+# Step 6: Create swap space
+if ! [ "$(sudo swapon -s)" ]; then
+  echo "Creating swap space..."
+  sudo mkdir /swap && sudo fallocate -l 24G /swap/swapfile && sudo chmod 600 /swap/swapfile || { echo "Failed to create swap space! Exiting..."; exit 1; }
+  sudo mkswap /swap/swapfile && sudo swapon /swap/swapfile || { echo "Failed to set up swap space! Exiting..."; exit 1; }
+  sudo bash -c 'echo "/swap/swapfile swap swap defaults 0 0" >> /etc/fstab' || { echo "Failed to update /etc/fstab! Exiting..."; exit 1; }
+fi
 
-# Step 8: Adjust network buffer sizes
+# Step 7: Adjust network buffer sizes
 echo "Adjusting network buffer sizes..."
 echo -e "\n# Increase buffer sizes for better network performance\nnet.core.rmem_max=600000000\nnet.core.wmem_max=600000000" | sudo tee -a /etc/sysctl.conf > /dev/null && sudo sysctl -p || { echo "Failed to adjust network buffer sizes! Exiting..."; exit 1; }
 
-# Step 9: Clone the repository
+# Step 8: Clone the repository
 echo "Cloning the repository..."
 cd "$HOME" || { echo "Failed to change directory to $HOME! Exiting..."; exit 1; }
 git clone https://github.com/QuilibriumNetwork/ceremonyclient.git || { echo "Failed to clone the repository! Exiting..."; exit 1; }
 cd ceremonyclient/node || { echo "Failed to change directory to ceremonyclient/node! Exiting..."; exit 1; }
 
-# Step 10: Run the node
+# Step 9: Run the node
 echo "Changing directory to $HOME/ceremonyclient/node..."
 cd "$HOME/ceremonyclient/node" || { echo "Failed to change directory to $HOME/ceremonyclient/node! Exiting..."; exit 1; }
 
@@ -52,7 +60,7 @@ echo "Running the node..."
 GOEXPERIMENT=arenas /usr/local/go/bin/go run ./... > /dev/null 2>&1 &  # Redirect output to /dev/null
 GO_PID=$!
 
-# Step 11: Letting the node run for 3 minutes
+# Step 10: Letting the node run for 3 minutes
 echo "Letting the node run for 3 minutes..."
 
 countdown() {
@@ -67,7 +75,7 @@ countdown() {
 
 countdown 180 || { echo "Failed to wait! Exiting..."; exit 1; }
 
-# Prompt for reboot
+# Step 11: Prompt for reboot
 echo "Node installation is finished."
 echo "Type 'sudo reboot' and press Enter to reboot your server."
 echo "Then login again and follow the instructions of the guide to restart your node."
