Update installer
small bugs

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -10,7 +10,7 @@ sudo apt install git -y || { echo "Failed to install git! Exiting..."; exit 1; }
 
 # Step 3: Install required packages
 echo "Installing required packages..."
-sudo apt-get install speedtest-cli htop tmux -y || { echo "Failed to install required packages! Exiting..."; exit 1; }
+sudo apt install speedtest-cli htop tmux -y || { echo "Failed to install required packages! Exiting..."; exit 1; }
 
 # Step 4: Download and extract Go
 echo "Downloading and extracting Go..."
@@ -45,7 +45,13 @@ cd ceremonyclient/node || { echo "Failed to change directory to ceremonyclient/n
 
 # Step 9: Run the Go program in the background
 echo "Running the Go program in the background..."
-GOEXPERIMENT=arenas /usr/local/go/bin/go run ./... & || { echo "Failed to run the Go program! Exiting..."; exit 1; }
+GOEXPERIMENT=arenas /usr/local/go/bin/go run ./... &
+GO_PID=$!
+
+if ! wait $GO_PID; then
+    echo "Failed to run the Go program! Exiting..."
+    exit 1
+fi
 
 # Step 10: Wait for a few seconds before proceeding
 echo "Letting the node run for 5 minutes..."
