Update installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -52,11 +52,11 @@ echo "Running the node..."
 GOEXPERIMENT=arenas /usr/local/go/bin/go run ./... > /dev/null 2>&1 &  # Redirect output to /dev/null
 GO_PID=$!
 
-# Step 11: Wait for a few seconds before proceeding
-echo "Letting the node run for 5 minutes..."
+# Step 11: Letting the node run for 3 minutes
+echo "Letting the node run for 3 minutes..."
 
 countdown() {
-    secs=$1         # Assign the input argument (300) to the variable 'secs'
+    secs=$1         # Assign the input argument (180) to the variable 'secs'
     while [ $secs -gt 0 ]; do
         printf "\r%02d:%02d remaining" $(($secs/60)) $(($secs%60)) # Print the remaining time (mm:ss) with a carriage return (\r) to overwrite the previous line
         sleep 1     # Wait for 1 second
@@ -65,7 +65,7 @@ countdown() {
     printf "\nDone!\n" # After the countdown completes, print "Done!" on a new line
 }
 
-countdown 300 || { echo "Failed to wait! Exiting..."; exit 1; }
+countdown 180 || { echo "Failed to wait! Exiting..."; exit 1; }
 
 # Prompt for reboot
 echo "Node installation is finished."
