Update installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -69,7 +69,25 @@ countdown() {
 
 countdown 300 || { echo "Failed to wait! Exiting..."; exit 1; }
 
+# Step 12: Enable gRPC
+echo "Enabling gRPC..."
+cd "$HOME/ceremonyclient/node" || { echo "Failed to change directory to ~/ceremonyclient/node! Exiting..."; exit 1; }
+sudo sed -i 's#^listenGrpcMultiaddr:.*$#listenGrpcMultiaddr: /ip4/127.0.0.1/tcp/8337#' .config/config.yml || { echo "Failed to enable gRPC! Exiting..."; exit 1; }
+
+# Step 12b: Enable Stats Collection
+echo "Enabling Stats Collection..."
+sudo sed -i 's#^  engine:$#  engine:\n    statsMultiaddr: "/dns/stats.quilibrium.com/tcp/443"#' .config/config.yml || { echo "Failed to enable Stats Collection! Exiting..."; exit 1; }
+
+# Step 13: Configure Firewall
+echo "Configuring firewall..."
+echo "y" | sudo ufw enable || { echo "Failed to enable firewall! Exiting..."; exit 1; }
+sudo ufw allow 22
+sudo ufw allow 8336
+sudo ufw allow 443
+sudo ufw status
+
 # Prompt for reboot
 echo "Node installation is finished."
 echo "Type 'sudo reboot' and press Enter to reboot your server."
 echo "Then login again and follow the instructions of the guide to restart your node."
+echo "Remember to download and keep safe your keys.yml and config.yml files!"
