Update server_setup

diff --git a/server_setup b/server_setup
--- a/server_setup
+++ b/server_setup
@@ -36,8 +36,20 @@ if [[ $(go version) == *"go1.20.1"* || $(go version) == *"go1.20.2"* || $(go ver
   echo "✅ Correct version of Go is already installed, moving on..."
 else
   echo "⬇️ Installing the necessary version of Go..."
+
+  # Download the Go tarball
   wget -4 https://go.dev/dl/go1.20.14.linux-amd64.tar.gz || { echo "❌ Failed to download Go! Exiting..."; exit_message; exit 1; }
+
+  # Remove the existing Go installation if it exists
+  if [ -d "/usr/local/go" ]; then
+    echo "🧹 Removing existing Go installation..."
+    sudo rm -rf /usr/local/go || { echo "❌ Failed to remove existing Go installation! Exiting..."; exit_message; exit 1; }
+  fi
+
+  # Extract the new Go tarball
   sudo tar -C /usr/local -xzf go1.20.14.linux-amd64.tar.gz || { echo "❌ Failed to extract Go! Exiting..."; exit_message; exit 1; }
+
+  # Clean up the downloaded tarball
   sudo rm go1.20.14.linux-amd64.tar.gz || { echo "❌ Failed to remove downloaded archive! Exiting..."; exit_message; exit 1; }
 fi
 
