Update store_kickstart
moved store.zip download to the beginning

diff --git a/store_kickstart b/store_kickstart
--- a/store_kickstart
+++ b/store_kickstart
@@ -1,13 +1,34 @@
 #!/bin/bash
 
 # Step 0: Welcome
-echo "✨ Welcome! This script will changed your Qnode store folder with another one for fast syncing. ✨"
-echo "You must be running the node as a service, otherwise the script won't work"
-echo "If you are not running as a service, follow the step by step process at https://iri.quest/qnode-store" 
+echo "✨ Welcome! This script will change your Qnode store folder with another one for fast syncing. ✨"
+echo "You must be running the node as a service, otherwise the script won't work."
+echo "If you are not running as a service, follow the step-by-step process at https://iri.quest/qnode-store."
 echo "Made with 🔥 by LaMat"
 echo ""
 echo "Processing... ⏳"
 sleep 7  # Add a 7-second delay
+
+# Function to handle errors and exit the script
+handle_error() {
+    echo "❌ Error occurred in script at line: $1"
+    echo "ℹ️ Error message: $2"
+    exit 1
+}
+
+# Trap errors and call the handle_error function
+trap 'handle_error $LINENO "$BASH_COMMAND"' ERR
+
+# Download store from the internet
+echo "🌐 Downloading store from the internet..."
+wget -P ~/ceremonyclient/node/.config https://snapshots.cherryservers.com/quilibrium/store.zip || {
+    echo "❌ It was not possible to download the store.zip from the internet."
+    echo "If you have a store.zip locally, please proceed with the step-by-step method instead and use that one."
+    echo "More info on this page https://iri.quest/qstore-upload"
+    exit 1
+}
+echo "✅ Download completed successfully."
+sleep 1
 
 # Check if ceremonyclient service exists
 if ! systemctl list-unit-files | grep -q 'ceremonyclient.service'; then
@@ -29,29 +50,6 @@ if ! command -v unzip &> /dev/null; then
     sudo apt-get update && sudo apt-get install -y unzip || handle_error $LINENO "Failed to install unzip utility."
     echo "✅ Unzip utility installed successfully."
 fi
-
-# Function to handle errors and exit the script
-handle_error() {
-    echo "❌ Error occurred in script at line: $1"
-    echo "ℹ️ Error message: $2"
-    exit 1
-}
-
-# Trap errors and call the handle_error function
-trap 'handle_error $LINENO "$BASH_COMMAND"' ERR
-
-# Check if store.zip already exists and overwrite if it does
-if [ -f ~/ceremonyclient/node/.config/store.zip ]; then
-    echo "⚠️ store.zip already exists. Overwriting..."
-    rm ~/ceremonyclient/node/.config/store.zip
-    echo "✅ Previous store.zip deleted successfully."
-fi
-
-# Download store from the internet
-echo "🌐 Downloading store from the internet..."
-wget -P ~/ceremonyclient/node/.config https://snapshots.cherryservers.com/quilibrium/store.zip
-echo "✅ Download completed successfully."
-sleep 1
 
 # Stop node service if it's not already stopped
 if systemctl is-active --quiet ceremonyclient; then
@@ -77,7 +75,6 @@ sleep 1
 echo "📦 Extracting archive in store folder..."
 cd ~/ceremonyclient/node/.config
 unzip store.zip -d . > /dev/null
-# unzip store.zip -d store > /dev/null - this creates a nested store/store folder
 echo "✅ Archive extracted successfully."
 
 # Delete store.zip
@@ -87,7 +84,7 @@ echo "✅ store.zip deleted successfully."
 
 # Delete store-original if it exists
 echo "🗑️ Deleting store-original if it exists..."
-if [ -d ~/ceremonyclient/node/.config/store-original ]; then
+if [ -d ~/ceremonyclient/node/.config/store-original]; then
     rm -rf ~/ceremonyclient/node/.config/store-original
     echo "✅ 'store-original' folder deleted successfully."
 else
