Update qnode_set_gRPC_calls

diff --git a/tools/qnode_set_gRPC_calls b/tools/qnode_set_gRPC_calls
--- a/tools/qnode_set_gRPC_calls
+++ b/tools/qnode_set_gRPC_calls
@@ -5,9 +5,9 @@ line_exists() {
     grep -qF "$1" "$2"
 }
 
-# Function to delete a line from a file
-delete_line() {
-    sudo sed -i "/$1/d" "$2" || { echo "❌ Failed to delete line containing '$1'! Exiting..."; exit 1; }
+# Function to add a line after a specific pattern
+add_line_after_pattern() {
+    sudo sed -i "/^ *$1:/a\  $2" "$3" || { echo "❌ Failed to add line after '$1'! Exiting..."; exit 1; }
 }
 
 # Step 1: Enable gRPC and REST
@@ -15,9 +15,9 @@ echo "🚀 Enabling gRPC and REST..."
 sleep 1
 cd "$HOME/ceremonyclient/node" || { echo "❌ Failed to change directory to ~/ceremonyclient/node! Exiting..."; exit 1; }
 
-# Delete existing lines for listenGrpcMultiaddr and listenRESTMultiaddr
-delete_line "listenGrpcMultiaddr:" .config/config.yml
-delete_line "listenRESTMultiaddr:" .config/config.yml
+# Delete existing lines for listenGrpcMultiaddr and listenRESTMultiaddr if they exist
+sudo sed -i '/^ *listenGrpcMultiaddr:/d' .config/config.yml
+sudo sed -i '/^ *listenRESTMultiaddr:/d' .config/config.yml
 
 # Add listenGrpcMultiaddr: "/ip4/127.0.0.1/tcp/8337"
 echo "listenGrpcMultiaddr: \"/ip4/127.0.0.1/tcp/8337\"" | sudo tee -a .config/config.yml > /dev/null || { echo "❌ Failed to enable gRPC! Exiting..."; exit 1; }
@@ -29,21 +29,13 @@ sleep 1
 
 # Step 2: Enable Stats Collection
 echo "📊 Enabling Stats Collection..."
-if ! line_exists "  statsMultiaddr: \"/dns/stats.quilibrium.com/tcp/443\"" .config/config.yml; then
-    sudo sed -i '/^ *engine:/a\  statsMultiaddr: "/dns/stats.quilibrium.com/tcp/443"' .config/config.yml || { echo "❌ Failed to enable Stats Collection! Exiting..."; exit 1; }
+if ! line_exists "statsMultiaddr: \"/dns/stats.quilibrium.com/tcp/443\"" .config/config.yml; then
+    add_line_after_pattern "engine" "statsMultiaddr: \"/dns/stats.quilibrium.com/tcp/443\"" .config/config.yml
+    echo "✅ Stats Collection enabled."
 else
     echo "✅ Stats Collection already enabled."
 fi
 
 sleep 1
 
-# Check if all lines were added successfully and are correct
-if line_exists "listenGrpcMultiaddr: \"/ip4/127.0.0.1/tcp/8337\"" .config/config.yml && line_exists "listenRESTMultiaddr: \"/ip4/127.0.0.1/tcp/8338\"" .config/config.yml && line_exists "  statsMultiaddr: \"/dns/stats.quilibrium.com/tcp/443\"" .config/config.yml; then
-    echo "✨ Success: The script successfully edited your config.yml file."
-else
-    echo "❌ ERROR: The script failed to correctly edit your config.yml file or there are typos."
-    echo "You may want to follow the online guide to do it manually."
-    exit 1
-fi
-
-echo "✅ gRPC and REST calls setup was successful."
+echo "✅ gRPC, REST, and Stats Collection setup was successful."
